mysite/myapp/urls.py
from django.urls import path
from django.contrib import admin
from .views import RegistUserView, HomeView, UserLoginView, UserLogoutView, UserView, CreatePostView, PostListView, EditPostView, DeletePostView
from . import views

app_name = 'myapp'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('change_password/', views.change_password, name='change_password'),
    path('user/', UserView.as_view(), name='user'),
    path('create_post/', CreatePostView.as_view(), name='create_post'),
    path('list_posts/', PostListView.as_view(), name='list_posts'),
    path('edit_post<int:id>/', EditPostView.as_view(), name='edit_post'),
    path('delete_post/<int:id>/', DeletePostView.as_view(), name='delete_post'),
    path('post_comments/<int:post_id>', views.post_comments, name='post_comments'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('', RedirectView.as_view(url='/myapp/home/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/forms.py
from django import forms
from .models import Users, Posts, Comments
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError


class RegistForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    
    class Meta:
        model = Users
        fields = ['username', 'email', 'password']
        
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    

class UserLoginForm(forms.Form):
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    
class UserEditForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    email = forms.EmailField(label='メールアドレス')

    class Meta:
        model = Users
        fields = ['username', 'email']
        
class PasswordChangeForm(forms.ModelForm):

    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())
    
    class Meta():
        model = Users
        fields = ['password', ]
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります。')

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    
class CreatePostForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    content = forms.CharField(label='コンテンツ', widget=forms.Textarea)
    image = forms.ImageField(label='写真')
    
    class Meta:
        model = Posts
        fields = ['title', 'content', 'image']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].required = False
        
class EditPostForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    content = forms.CharField(label='コンテンツ', widget=forms.Textarea)
    image = forms.ImageField(label='写真')
    class Meta:
        model = Posts
        fields = ['title', 'content', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].required = False
        self.fields['content'].required = False
        self.fields['image'].required = False
        
class DeletePostForm(forms.ModelForm):
    confirm_delete = forms.BooleanField(label='削除を確認する', required=True)
    
    class Meta:
        model = Posts
        fields = []
        
class PostCommentForm(forms.ModelForm):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 5, 'cols': 60}))
    
    class Meta:
        model = Comments
        fields = ('comment',)

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <title>Car Journey Linker</title>
    <meta name="description" content="ここにサイトの説明を書く">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="logo">
        <img src="{% static 'images/logofortop.png' %}" alt="Logo">
    </div>
    <div>
        <h1>Car Journey Linker</h1>
    </div>
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li><a class="navbar-brand" href="{% url 'myapp:home' %}">ホーム</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="navbar-brand" href="{% url 'myapp:user' %}">マイページ</a></li>
                        <li><a class="navbar-brand" href="{% url 'myapp:user_logout' %}">ログアウト</a></li>
                    {% else %}
                        <li><a class="navbar-brand" href="{% url 'myapp:user_login' %}">ログイン</a></li>
                        <li><a class="navbar-brand" href="{% url 'myapp:regist' %}">新規登録</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>

</html>

mysite/templates/change_password.html
{% extends "base.html" %}
{% block content %}
<body>
  <form method="POST">
    {% csrf_token %}
    <div class="form-all">
      <h3>パスワード変更</h3>
      <div class="password-editbox">
        <label for="id_password">パスワード</label>
        <input type="password" name="password" required id="id_password">
        <label for="id_confirm_password">パスワード再入力</label>
        <input type="password" name="confirm_password" required id="confirm_password">
        <input type="submit" value="パスワード更新">
      </div>
    </div>
  </form>
</body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

mysite/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="post-container">
        <h2>投稿画面</h2>
        <form action="{% url 'myapp:create_post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">タイトル:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_content">内容:</label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label for="id_image">写真を選択:</label>
                {{ form.image }}
            </div>
            <button type="submit" class="btn btn-primary">投稿する</button>
        </form>
    </div>
{% endblock %}

mysite/templates/delete_post.html
{% extends 'base.html' %}
{% block content %}
    <div class="post-container">
        <h2>投稿削除最終確認</h2>
        <div class="delete-check">削除を実行する場合はチェックを入れて削除ボタンを押して下さい</div>
        <form method="POST">
        {% csrf_token %}
        {{ delete_post_form.as_p }}
        <button type="submit" class="delete-post">削除する</button>
        </form>
{% endblock %}

mysite/templates/edit_post.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="post-container">
    <h2>投稿内容編集画面</h2>
    <form action="{% url 'myapp:edit_post' post.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">タイトル:</label>
            {{ form.title }}
        </div>
        <div class="form-image">
            <label for="id_content">内容:</label>
            {{ form.content }}
        </div>
        <div class="form-group">
            <label for="id_image">写真を選択:</label>
            {{ form.image }}
            {% if post.image %}
                <img class="post-img" src="{{ post.image.url }}" alt="Post image">
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">更新</button>
        <div class="btn-delete">
        <a href="{% url 'myapp:delete_post' post.id %}">削除</a>
        </div>
    </form>
</div>
{% endblock %}

mysite/templates/home.html
{% extends 'base.html' %}
{% block content %}
<body>
    {% load static %}
    <div class="header-img">
        <img src="{% static 'images/header1.jpg' alt=' ' %}">
    </div>

    <div class="container">
        <h2>Car Journey Linkerについて</h2>
    </div>
    <div class="explain-thispage">Car Journey Linkerでは、ご自身の車旅の思い出を投稿し経験を共有しつつ、その旅の注意点や、おすすめポイントなどを共有するサイトです。
    投稿一覧を見るためには登録及びログインが必要です。</div>
</body>
{% endblock %}

mysite/templates/list_posts.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<h3>投稿一覧画面</h3>

<div class="list-info">
    <p>タイトルをクリックすると投稿内容へ</p>
    <p>作成者の名前をクリックすると編集＆削除画面へ（作成者のみ可能）</p>
</div>

<div class="list-container">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>タイトル</th>
                <th>作成者</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td><a href="{% url 'myapp:post_comments' post_id=post.id %}">{{ post.title }}</a></td>
                {% if post.user.id == user.id %}
                    <td><a href="{% url 'myapp:edit_post' id=post.id %}">{{ post.user.username }}</a></td>
                {% else %}
                    <td>{{ post.user.username }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mysite/templates/post_comments.html
{% extends 'base.html' %}
{% block content %}
<div class="post-comment">
    <h6>{{ post.title }}</h6>
    <div class="post-content">
        <p>{{ post.content| linebreaksbr }}</p>
    </div>
    <div>
        {% if post.image %}
            <img class="post-img" src="{{ post.image.url }}" alt="Post image">
        {% endif %}
    </div>

    <h7>コメント</h7>

    <ul class="comments">
        {% for comment in comments %}
            <li class="comment">
                <div class="comment-header">
                    {{ comment.user.username }} {{ comment.created_at|date:"Y/m/d H:i" }}
                </div>
                <div class="comment-content">
                    {{ comment.comment | linebreaksbr}}
                </div>
            </li>
        {% empty %}
            <li>まだコメントはありません。</li>
        {% endfor %}
    </ul>
    <h7>コメントを追加</h7>
    <form method="POST" class="comment-form">
        {% csrf_token %}
        {{ post_comment_form.as_p }}
        <input type="submit" value="コメント送信">
    </form>

    <div class="back-button">
        <a href="{% url 'myapp:list_posts'%}">戻る</a>
    </div>
</div>
{% endblock %}

mysite/templates/regist.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
{% endif %}
<body>
<form method="POST">
{% csrf_token %}
<div class="form-all">
    <h3>新規登録</h3>
    <div>
    <div class="form-registbox">        
        <label for="id_username">ユーザー名</label>
        <input type="text" name="username" maxlength="150" requied id="id_username">
        <label for="id_email">メールアドレス</label>
        <input type="email" name="email" maxlength="255" required id="id_email">
        <label for="id_password">パスワード</label>
        <input type="password" name="password" required id="id_password">
        <input type="submit" name="" value="新規登録">
    </div>
</form>
</body>
{% endblock %}

mysite/templates/user.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="user-container">
        <h4 class="username-heading">{{ user.username }}のマイページ</h4>
        <div class="card" onclick="location.href='{% url 'myapp:user_edit' %}'">
            <h5>ユーザー情報変更</h5>
            <p>ユーザー情報の更新が行えます。</p>
        </div>
        <div class="card" onclick="location.href='{% url 'myapp:change_password' %}'">
            <h5>パスワード変更</h5>
            <p>パスワードを変更が行えます。</p>
        </div>
        <div class="card" onclick="location.href='{% url 'myapp:create_post' %}'">
            <h5>投稿画面</h5>
            <p>新しい投稿を作成できます。</p>
        </div>
        <div class="card" onclick="location.href='{% url 'myapp:list_posts' %}'">
            <h5>投稿一覧</h5>
            <p>投稿一覧を表示します。</p>
        </div>
    </div>
</body>
</html>
{% endblock %}

mysite/templates/user_edit.html
{% extends "base.html" %}
{% block content %}
<body>
  <form method="POST">
    {% csrf_token %}
    <div class="form-all">
      <h3>ユーザー情報変更</h3>
      <div class="user-editbox">
        <label for="id_username">ユーザー名</label>
        <input type="text" name="username" maxlength="150" required id="id_username">
        <label for="id_email">メールアドレス</label>
        <input type="email" name="email" maxlength="255" required id="id_email">
        <input type="submit" value="更新">
      </div>
    </div>
  </form>
</body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

mysite/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<body>
<form method="POST">
{% csrf_token %}
    <div class="form-all">
        <h3>ログインフォーム</h3>
    <input type="hidden" mame="next" value="{{ request.GET.next }}">
        <div class="form-loginbox">
            <label for="id_email">メールアドレス</label>
            <input type="email" name="email" maxlength="255" required id="id_email">
            <label for="id_password">パスワード</label>
            <input type="password" name="password" required id="id_password">
            <input type="submit" name="" value="ログイン">
        </div>
</form>
</body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}